### ISSUE TITLE
Consider adding `mypy`

### ISSUE THREAD

**Issue by thepabloaguilar** [quintoandar/butterfree#195]
# Consider adding `mypy`

## Summary

> TL;DR: A simple summary about the tech debt

**Age:** new-tech-debt-introduced

**Estimated cost:** investigation_needed

**Type:** coding and testing

### Description :clipboard:

`butterfree` adopted type hints, we have to guarantee those types are right.
The users can have some problems when they'll use it in a typed context and using `mypy`.

### Impact :bomb:

**Critical when** people will use this lib in a typed context and lib has wrong type hints!

### Solution Hints :shipit:

Add mypy check

---

Modules with wrong types to fix:

- [ ] configs
- [ ] validations
- [x] constants
- [ ] dataframe_service
- [ ] reports
- [ ] extract
- [x] clients
- [ ] load
- [ ] transform
- [ ] pipelines
- [ ] testing

I can fix this issue, if possible!

**Comment by guilhermesalerno** [comment]
Thanks for submitting the issue! 
We'd appreciate if you are able to work on it :)

**Comment by thepabloaguilar** [comment]
One example of wrong type is the `_get_create_table_query` method:
```python
class CassandraClient(AbstractClient):
    def _get_create_table_query(self, columns: dict, table: str):
        """Creates CQL statement to create a table."""
        parsed_columns = []
        primary_keys = []

        for col in columns:
            col_str = f"{col['column_name']} {col['type']}"
            if col["primary_key"]:
                primary_keys.append(col["column_name"])
            parsed_columns.append(col_str)

        parsed_columns = ", ".join(parsed_columns)

        if len(primary_keys) > 0:
            primary_keys = ", ".join(primary_keys)
            columns_str = f"{parsed_columns}, PRIMARY KEY ({primary_keys})"
        else:
            columns_str = parsed_columns

        query = f"CREATE TABLE {self.cassandra_key_space}.{table} " f"({columns_str}); "

        return query
```

The `columns` argument has a wrong type, current type is `dict` but in fact it's `List[Dict[str, str]]`. You can see this in the `for` loop.
Thanks mypy:
```sh
mypy butterfree/clients/cassandra_client.py
...
butterfree/clients/cassandra_client.py:106: error: Function is missing a return type annotation
butterfree/clients/cassandra_client.py:112: error: Invalid index type "str" for "str"; expected type "Union[int, slice]"
butterfree/clients/cassandra_client.py:113: error: Invalid index type "str" for "str"; expected type "Union[int, slice]"
butterfree/clients/cassandra_client.py:114: error: Invalid index type "str" for "str"; expected type "Union[int, slice]"
...
```
