### ISSUE TITLE
request: Is it possible to use this lib with databricks-connect?

### ISSUE THREAD

**Issue by diogo-lucena-wildlife** [quintoandar/butterfree#314]
First of all: Congratulation on building this lib. 
So far this seems an awesome lib and I'm thinking about using it in one of our projects.

I'm creating a repo that uses a tool called [databricks-connect](https://docs.databricks.com/dev-tools/databricks-connect.html#language-python) that allows us to develop locally while running all the heavy processing on top of Databricks clusters. The idea behind this work is to be able to create an image that allow us to easily  run the same code  locally, on deploy pipelines and also on Airflows DAGs.

Do you have any use case like this at 5A?

btw, the link for pre processing in this page is broken: https://butterfree.readthedocs.io/en/latest/extract.html

thanks =D

**Comment by moromimay** [comment]
Hi @diogo-lucena-wildlife, thanks for your interest in using Butterfree :heart_eyes_cat:  

Here we use Databricks + Airflow, but we don't use `databricks-connect` and reading this [documentation](https://docs.databricks.com/dev-tools/databricks-connect.html#conflicting-pyspark-installations), says that it is in conflict with PySpark, so I don't recommend using Butterfree with databricks-connect as you may have some problems.

About the link in our documentation, let's will fix it :rocket:  

Thank you very much for your attention :smiley_cat:

**Comment by diogo-lucena-wildlife** [comment]
Actually, databricks-connect provides its own pyspark lib.
What I had to do to make them work together, was to first uninstall the pyspark that came with Buterfree, than install databricks-connect.
Once this is done, I needed to create my own SparkSession so the "getOrCreate" on buterfree's client can use it.

Also for some reason, this 2 packages were missing and I had to install them manually: typing_extensions and h3
Not sure this happened because I've uninstalled Buterfrees Spark or if they're just missing

Thanks ^^

**Comment by moromimay** [comment]
> Actually, databricks-connect provides its own pyspark lib.
> What I had to do to make them work together, was to first uninstall the pyspark that came with Buterfree, than install databricks-connect.
> Once this is done, I needed to create my own SparkSession so the "getOrCreate" on buterfree's client can use it.
> 
> Also for some reason, this 2 packages were missing and I had to install them manually: typing_extensions and h3
> Not sure this happened because I've uninstalled Buterfrees Spark or if they're just missing
> 
> Thanks ^^

Nice, did you have a problem using the two (Butterfree + databricks-connect) together? :thinking: :thought_balloon: 

About the packages:

- h3: You need to install Butterfree this way: `pip install butterfree[h3]==<version>`
- typing_extensions: We fixed this but only in our development version. Soon we will send it to production!

**Comment by diogo-lucena-wildlife** [comment]
So far, no problems at all but I've just started working with them ^^

The only catch is that if I use HistoricalFeatureStoreWriter(debug_mode=True) I can't simply go to databricks, open a notebook and access the generated table, but its possible to [integrate](https://docs.databricks.com/repos.html) databricks with GIT, pull code and run there for developing.
And since the table is available in the cluster, automated tests won't be a problem.

So it seems we'll be able to use the lib =D

thank you for the project
