### ISSUE TITLE
S3Config class is missing

### ISSUE THREAD

**Issue by diogo-lucena-wildlife** [quintoandar/butterfree#317]
By following: https://butterfree.readthedocs.io/en/latest/configuration.html I should be able to create an S3Config class to send data to S3 but theres no implementation for this class.

Also: to which S3 Actions I'll need permissions to save the table?

thanks =D

**Comment by roelschr** [comment]
Hi @diogo-lucena-wildlife, thank you for opening this issue.

The S3Config was renamed to [MetastoreConfig](https://github.com/quintoandar/butterfree/blob/8077d8656fc4b6f5259f991c9797b90fe8e9b67c/butterfree/configs/db/metastore_config.py), with s3 as the default storage.

We probably forgot to update this section of the documentation, I apologize. We'll be updating the documentation asap :)
