### ISSUE TITLE
Transform a feature before aggregating it

### ISSUE THREAD

**Issue by diogo-lucena-wildlife** [quintoandar/butterfree#323]
Hello everyone

Is it possible to transform (using the sql or spark transform) a data before aggregating it?

example, I want to aggregate using the max operator, but my numerical field is actually a string that I must cast to integer first.
What I'm doing right now is casting the value on the query and aggregating it on the featureSet but I'd like, if possible, to keep the queries as simple as possible.

Or like, I have a column that is one of 10 possible words and I want to use a case statement to transform it into a number and then aggregate using max.

Thanks =D

**Comment by moromimay** [comment]
Hii @diogo-lucena-wildlife :smiley_cat: 

The transformations that can be applied at Source are called pre_processing and you can find them [here](https://butterfree.readthedocs.io/en/latest/butterfree.extract.pre_processing.html).

In your case, you can follow the logic you are doing in the Source query, or you can just CAST the query and use CASE as a filter expression in the aggregate feature. The filter expression you can find [here](https://butterfree.readthedocs.io/en/latest/butterfree.transform.transformations.html#butterfree.transform.transformations.aggregated_transform.AggregatedTransform.filter_expression).

If you need some transformation that we don't support at the moment, feel free to open an Issue or contribute to Butterfree :wink:
